spring:
  datasource:
    url: jdbc:mysql://localhost:3306/picpay
    username: root
    password: darskull1
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true